import JSZip from "jszip";
import type { ExtractedSite, ThemeFile } from "./types";

/** Original image URL -> filename inside assets/, for images that imported cleanly. */
export type AssetMap = Record<string, string>;

/** Liquid/JSON is generated as data, so anything from the source page is escaped. */
function esc(value: string): string {
  return (value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function json(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function layout(site: ExtractedSite): string {
  return `<!doctype html>
<html lang="{{ request.locale.iso_code }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ page_title }}{% if current_page != 1 %} &ndash; {{ current_page }}{% endif %}</title>
    {% if page_description %}<meta name="description" content="{{ page_description | escape }}">{% endif %}
    <link rel="canonical" href="{{ canonical_url }}">
    {{ content_for_header }}
    {{ 'theme.css' | asset_url | stylesheet_tag }}
  </head>
  <body class="template-{{ template.name }}">
    <a class="skip-link" href="#main">Skip to content</a>
    {% section 'header' %}
    <main id="main">
      {{ content_for_layout }}
    </main>
    {% section 'footer' %}
    {{ 'theme.js' | asset_url | script_tag }}
  </body>
</html>
<!-- Generated by the W3Tech Shopify Theme Generator from ${esc(site.sourceUrl)} -->
`;
}

function headerSection(site: ExtractedSite, assets: AssetMap): string {
  const linkBlocks = site.header.links.map((link) => ({
    type: "link",
    settings: { label: link.label, url: link.href },
  }));

  return `<header class="site-header">
  <div class="wrapper site-header__inner">
    <a class="site-header__brand" href="{{ routes.root_url }}">
      {%- if section.settings.logo -%}
        {{ section.settings.logo | image_url: width: 240 | image_tag: alt: shop.name, class: 'site-header__logo' }}
      {%- elsif section.settings.logo_asset != blank -%}
        <img class="site-header__logo" src="{{ section.settings.logo_asset | asset_url }}" alt="{{ shop.name | escape }}">
      {%- else -%}
        {{ section.settings.brand | default: shop.name }}
      {%- endif -%}
    </a>
    <nav class="site-header__nav">
      {%- for block in section.blocks -%}
        <a href="{{ block.settings.url }}" {{ block.shopify_attributes }}>{{ block.settings.label }}</a>
      {%- endfor -%}
    </nav>
    <a class="site-header__cart" href="{{ routes.cart_url }}">Cart ({{ cart.item_count }})</a>
  </div>
</header>

{% schema %}
${json({
  name: "Header",
  settings: [
    { type: "image_picker", id: "logo", label: "Logo" },
    { type: "text", id: "logo_asset", label: "Imported logo file", default: assets[site.header.logo?.src || ""] || "" },
    { type: "text", id: "brand", label: "Brand name", default: site.brand },
  ],
  blocks: [
    {
      type: "link",
      name: "Menu link",
      settings: [
        { type: "text", id: "label", label: "Label", default: "Shop" },
        { type: "url", id: "url", label: "Link" },
      ],
    },
  ],
  default: { blocks: linkBlocks },
})}
{% endschema %}
`;
}

function heroSection(site: ExtractedSite, assets: AssetMap): string {
  const hero = site.hero;

  return `<section class="hero" style="--hero-image: url('{{ section.settings.image | image_url: width: 1600 }}')">
  <div class="wrapper hero__inner">
    <div class="hero__text">
      <h1>{{ section.settings.heading }}</h1>
      {%- if section.settings.subheading != blank -%}
        <p>{{ section.settings.subheading }}</p>
      {%- endif -%}
      {%- if section.settings.cta_label != blank -%}
        <a class="button" href="{{ section.settings.cta_url }}">{{ section.settings.cta_label }}</a>
      {%- endif -%}
    </div>
    {%- if section.settings.image -%}
      <div class="hero__media">
        {{ section.settings.image | image_url: width: 1200 | image_tag: alt: section.settings.heading }}
      </div>
    {%- elsif section.settings.image_asset != blank -%}
      <div class="hero__media">
        <img src="{{ section.settings.image_asset | asset_url }}" alt="{{ section.settings.heading | escape }}" loading="eager">
      </div>
    {%- elsif section.settings.image_url != blank -%}
      <div class="hero__media">
        <img src="{{ section.settings.image_url }}" alt="{{ section.settings.heading | escape }}" loading="eager">
      </div>
    {%- endif -%}
  </div>
</section>

{% schema %}
${json({
  name: "Hero",
  settings: [
    { type: "text", id: "heading", label: "Heading", default: hero?.heading || "Your headline here" },
    {
      type: "textarea",
      id: "subheading",
      label: "Subheading",
      default: hero?.subheading || "Describe what you sell in a sentence.",
    },
    { type: "image_picker", id: "image", label: "Image (upload to replace the imported file)" },
    {
      type: "text",
      id: "image_asset",
      label: "Imported image file",
      info: "Served from the theme's assets/ directory.",
      default: assets[hero?.image?.src || ""] || "",
    },
    {
      type: "text",
      id: "image_url",
      label: "Source image URL",
      info: "Fallback used only when the image could not be downloaded into assets/.",
      default: assets[hero?.image?.src || ""] ? "" : hero?.image?.src || "",
    },
    { type: "text", id: "cta_label", label: "Button label", default: hero?.ctaLabel || "Shop now" },
    { type: "url", id: "cta_url", label: "Button link" },
  ],
  presets: [{ name: "Hero" }],
})}
{% endschema %}
`;
}

function imageWithTextSection(site: ExtractedSite, assets: AssetMap): string {
  const block = site.imageWithText;

  return `<section class="image-with-text">
  <div class="wrapper image-with-text__inner">
    <div class="image-with-text__media">
      {%- if section.settings.image -%}
        {{ section.settings.image | image_url: width: 900 | image_tag: alt: section.settings.heading }}
      {%- elsif section.settings.image_asset != blank -%}
        <img src="{{ section.settings.image_asset | asset_url }}" alt="{{ section.settings.heading | escape }}" loading="lazy">
      {%- elsif section.settings.image_url != blank -%}
        <img src="{{ section.settings.image_url }}" alt="{{ section.settings.heading | escape }}" loading="lazy">
      {%- endif -%}
    </div>
    <div class="image-with-text__content">
      <h2>{{ section.settings.heading }}</h2>
      <div class="rte">{{ section.settings.body }}</div>
    </div>
  </div>
</section>

{% schema %}
${json({
  name: "Image with text",
  settings: [
    { type: "text", id: "heading", label: "Heading", default: block?.heading || "About the brand" },
    { type: "richtext", id: "body", label: "Body", default: `<p>${esc(block?.body || "Tell your story here.")}</p>` },
    { type: "image_picker", id: "image", label: "Image" },
    { type: "text", id: "image_asset", label: "Imported image file", default: assets[block?.image?.src || ""] || "" },
    {
      type: "text",
      id: "image_url",
      label: "Source image URL",
      default: assets[block?.image?.src || ""] ? "" : block?.image?.src || "",
    },
  ],
  presets: [{ name: "Image with text" }],
})}
{% endschema %}
`;
}

function featuredCollectionSection(site: ExtractedSite, assets: AssetMap): string {
  const cards = site.featured?.cards ?? [];

  return `<section class="featured">
  <div class="wrapper">
    <h2>{{ section.settings.heading }}</h2>

    {%- if section.settings.collection != blank -%}
      <div class="featured__grid">
        {%- for product in collections[section.settings.collection].products limit: section.settings.products_to_show -%}
          {% render 'card-product', product: product %}
        {%- endfor -%}
      </div>
    {%- else -%}
      {%- comment -%}
        No collection is connected yet, so the imported cards act as a placeholder.
        Pick a collection in the theme editor to switch to real products.
      {%- endcomment -%}
      <div class="featured__grid">
        {%- for block in section.blocks -%}
          <article class="card" {{ block.shopify_attributes }}>
            {%- if block.settings.image_asset != blank -%}
              <img src="{{ block.settings.image_asset | asset_url }}" alt="{{ block.settings.title | escape }}" loading="lazy">
            {%- elsif block.settings.image_url != blank -%}
              <img src="{{ block.settings.image_url }}" alt="{{ block.settings.title | escape }}" loading="lazy">
            {%- endif -%}
            <h3>{{ block.settings.title }}</h3>
            <p>{{ block.settings.body }}</p>
          </article>
        {%- endfor -%}
      </div>
    {%- endif -%}
  </div>
</section>

{% schema %}
${json({
  name: "Featured collection",
  settings: [
    { type: "text", id: "heading", label: "Heading", default: site.featured?.heading || "Featured" },
    { type: "collection", id: "collection", label: "Collection" },
    { type: "range", id: "products_to_show", label: "Products to show", min: 2, max: 12, step: 1, default: 4 },
  ],
  blocks: [
    {
      type: "card",
      name: "Imported card",
      settings: [
        { type: "text", id: "title", label: "Title" },
        { type: "textarea", id: "body", label: "Body" },
        { type: "text", id: "image_asset", label: "Imported image file" },
        { type: "text", id: "image_url", label: "Source image URL" },
      ],
    },
  ],
  presets: [{ name: "Featured collection" }],
  default: {
    blocks: cards.map((card) => {
      const imported = assets[card.image?.src || ""] || "";
      return {
        type: "card",
        settings: {
          title: card.title,
          body: card.body,
          image_asset: imported,
          image_url: imported ? "" : card.image?.src || "",
        },
      };
    }),
  },
})}
{% endschema %}
`;
}

function testimonialsSection(site: ExtractedSite): string {
  const items = site.testimonials?.items ?? [];

  return `<section class="testimonials">
  <div class="wrapper">
    <h2>{{ section.settings.heading }}</h2>
    <div class="testimonials__grid">
      {%- for block in section.blocks -%}
        <blockquote {{ block.shopify_attributes }}>
          <p>{{ block.settings.quote }}</p>
          {%- if block.settings.author != blank -%}<cite>{{ block.settings.author }}</cite>{%- endif -%}
        </blockquote>
      {%- endfor -%}
    </div>
  </div>
</section>

{% schema %}
${json({
  name: "Testimonials",
  settings: [
    {
      type: "text",
      id: "heading",
      label: "Heading",
      default: site.testimonials?.heading || "What our customers say",
    },
  ],
  blocks: [
    {
      type: "quote",
      name: "Quote",
      settings: [
        { type: "textarea", id: "quote", label: "Quote" },
        { type: "text", id: "author", label: "Author" },
      ],
    },
  ],
  presets: [{ name: "Testimonials" }],
  default: {
    blocks: (items.length
      ? items
      : [{ quote: "Add a customer quote here.", author: "Customer name" }]
    ).map((item) => ({ type: "quote", settings: { quote: item.quote, author: item.author } })),
  },
})}
{% endschema %}
`;
}

function faqSection(site: ExtractedSite): string {
  const items = site.faq?.items ?? [];

  return `<section class="faq">
  <div class="wrapper">
    <h2>{{ section.settings.heading }}</h2>
    {%- for block in section.blocks -%}
      <details {{ block.shopify_attributes }}>
        <summary>{{ block.settings.question }}</summary>
        <div class="rte">{{ block.settings.answer }}</div>
      </details>
    {%- endfor -%}
  </div>
</section>

{% schema %}
${json({
  name: "FAQ",
  settings: [
    { type: "text", id: "heading", label: "Heading", default: site.faq?.heading || "Frequently asked questions" },
  ],
  blocks: [
    {
      type: "item",
      name: "Question",
      settings: [
        { type: "text", id: "question", label: "Question" },
        { type: "richtext", id: "answer", label: "Answer" },
      ],
    },
  ],
  presets: [{ name: "FAQ" }],
  default: {
    blocks: (items.length
      ? items
      : [{ question: "Add a question", answer: "Add an answer" }]
    ).map((item) => ({
      type: "item",
      settings: { question: item.question, answer: `<p>${esc(item.answer)}</p>` },
    })),
  },
})}
{% endschema %}
`;
}

function footerSection(site: ExtractedSite): string {
  return `<footer class="site-footer">
  <div class="wrapper site-footer__inner">
    <nav class="site-footer__nav">
      {%- for block in section.blocks -%}
        <a href="{{ block.settings.url }}" {{ block.shopify_attributes }}>{{ block.settings.label }}</a>
      {%- endfor -%}
    </nav>
    <p class="site-footer__legal">{{ section.settings.copyright }}</p>
  </div>
</footer>

{% schema %}
${json({
  name: "Footer",
  settings: [{ type: "text", id: "copyright", label: "Copyright", default: site.footer.copyright }],
  blocks: [
    {
      type: "link",
      name: "Footer link",
      settings: [
        { type: "text", id: "label", label: "Label" },
        { type: "url", id: "url", label: "Link" },
      ],
    },
  ],
  default: {
    blocks: site.footer.links.map((link) => ({
      type: "link",
      settings: { label: link.label, url: link.href },
    })),
  },
})}
{% endschema %}
`;
}

function cardProductSnippet(): string {
  return `{%- comment -%}
  Renders one product card.
  Accepts: product - {Object} product object.
{%- endcomment -%}
<article class="card">
  <a href="{{ product.url }}">
    {%- if product.featured_image -%}
      {{ product.featured_image | image_url: width: 600 | image_tag: alt: product.title, loading: 'lazy' }}
    {%- endif -%}
    <h3>{{ product.title }}</h3>
    <p class="card__price">{{ product.price | money }}</p>
  </a>
</article>
`;
}

export function themeCss(site: ExtractedSite): string {
  return `:root {
  --accent: ${site.colors.accent};
  --background: ${site.colors.background};
  --text: ${site.colors.text};
  --wrapper: 1200px;
}

*, *::before, *::after { box-sizing: border-box; }
body { margin: 0; background: var(--background); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; }
img { max-width: 100%; height: auto; display: block; }
a { color: inherit; }
.wrapper { max-width: var(--wrapper); margin: 0 auto; padding: 0 24px; }
.skip-link { position: absolute; left: -9999px; }
.skip-link:focus { left: 8px; top: 8px; background: var(--accent); color: #fff; padding: 8px 12px; z-index: 10; }

.site-header__inner { display: flex; align-items: center; justify-content: space-between; gap: 24px; padding-block: 20px; }
.site-header__brand { font-weight: 700; text-decoration: none; font-size: 20px; }
.site-header__logo { max-height: 40px; width: auto; }
.site-header__nav { display: flex; gap: 20px; flex-wrap: wrap; }
.site-header__nav a, .site-header__cart { text-decoration: none; }

.hero__inner { display: grid; gap: 32px; padding-block: 64px; grid-template-columns: 1fr; align-items: center; }
.hero h1 { font-size: clamp(32px, 5vw, 56px); margin: 0 0 16px; line-height: 1.1; }
.button { display: inline-block; margin-top: 24px; padding: 14px 28px; background: var(--accent); color: #fff; text-decoration: none; border-radius: 999px; font-weight: 600; }

.image-with-text__inner { display: grid; gap: 32px; padding-block: 56px; }
.featured, .testimonials, .faq { padding-block: 56px; }
.featured__grid, .testimonials__grid { display: grid; gap: 24px; grid-template-columns: 1fr; }
.card { border: 1px solid rgba(0,0,0,.08); border-radius: 12px; padding: 16px; }
.card h3 { margin: 12px 0 8px; font-size: 18px; }
blockquote { margin: 0; border-left: 3px solid var(--accent); padding-left: 16px; }
cite { display: block; margin-top: 8px; font-style: normal; opacity: .7; }
details { border-bottom: 1px solid rgba(0,0,0,.08); padding: 16px 0; }
summary { cursor: pointer; font-weight: 600; }

.site-footer { border-top: 1px solid rgba(0,0,0,.08); margin-top: 56px; }
.site-footer__inner { display: flex; flex-wrap: wrap; gap: 16px; justify-content: space-between; padding-block: 32px; }
.site-footer__nav { display: flex; gap: 16px; flex-wrap: wrap; }

@media (min-width: 750px) {
  .hero__inner, .image-with-text__inner { grid-template-columns: 1fr 1fr; }
  .featured__grid, .testimonials__grid { grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); }
}
`;
}

function themeJs(): string {
  return `// Minimal theme behaviour. Shopify handles cart and checkout itself.
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('details').forEach((item) => {
    item.addEventListener('toggle', () => {
      if (!item.open) return;
      item.parentElement?.querySelectorAll('details[open]').forEach((other) => {
        if (other !== item) other.open = false;
      });
    });
  });
});
`;
}

const HOME_ORDER = ["hero", "image-with-text", "featured-collection", "testimonials", "faq"];

export function buildThemeFiles(
  site: ExtractedSite,
  authorizedBy: string,
  assets: AssetMap = {}
): ThemeFile[] {
  const indexTemplate = {
    sections: Object.fromEntries(HOME_ORDER.map((type) => [type, { type, settings: {} }])),
    order: HOME_ORDER,
  };

  return [
    { path: "layout/theme.liquid", contents: layout(site) },

    { path: "sections/header.liquid", contents: headerSection(site, assets) },
    { path: "sections/hero.liquid", contents: heroSection(site, assets) },
    { path: "sections/image-with-text.liquid", contents: imageWithTextSection(site, assets) },
    { path: "sections/featured-collection.liquid", contents: featuredCollectionSection(site, assets) },
    { path: "sections/testimonials.liquid", contents: testimonialsSection(site) },
    { path: "sections/faq.liquid", contents: faqSection(site) },
    { path: "sections/footer.liquid", contents: footerSection(site) },
    { path: "sections/main-product.liquid", contents: mainProductSection() },
    { path: "sections/main-collection.liquid", contents: mainCollectionSection() },
    { path: "sections/main-page.liquid", contents: mainPageSection() },

    { path: "snippets/card-product.liquid", contents: cardProductSnippet() },

    { path: "templates/index.json", contents: json(indexTemplate) },
    {
      path: "templates/product.json",
      contents: json({ sections: { main: { type: "main-product" } }, order: ["main"] }),
    },
    {
      path: "templates/collection.json",
      contents: json({ sections: { main: { type: "main-collection" } }, order: ["main"] }),
    },
    {
      path: "templates/page.json",
      contents: json({ sections: { main: { type: "main-page" } }, order: ["main"] }),
    },

    { path: "config/settings_schema.json", contents: settingsSchema(site) },
    {
      path: "config/settings_data.json",
      contents: json({ current: { accent_color: site.colors.accent, text_color: site.colors.text } }),
    },

    { path: "assets/theme.css", contents: themeCss(site) },
    { path: "assets/theme.js", contents: themeJs() },
    {
      path: "assets/conversion-manifest.json",
      contents: json({
        generator: "W3Tech Shopify Theme Generator",
        sourceUrl: site.sourceUrl,
        convertedAt: site.extractedAt,
        authorizedBy,
        importedAssets: assets,
        detected: {
          hero: Boolean(site.hero),
          imageWithText: Boolean(site.imageWithText),
          featuredCards: site.featured?.cards.length ?? 0,
          testimonials: site.testimonials?.items.length ?? 0,
          faq: site.faq?.items.length ?? 0,
          headerLinks: site.header.links.length,
          footerLinks: site.footer.links.length,
        },
        warnings: site.warnings,
      }),
    },
  ];
}

function mainProductSection(): string {
  return `<section class="wrapper product">
  <h1>{{ product.title }}</h1>
  {%- if product.featured_image -%}
    {{ product.featured_image | image_url: width: 900 | image_tag: alt: product.title }}
  {%- endif -%}
  <p class="product__price">{{ product.price | money }}</p>
  <div class="rte">{{ product.description }}</div>

  {%- form 'product', product -%}
    <input type="hidden" name="id" value="{{ product.selected_or_first_available_variant.id }}">
    <button class="button" type="submit" {% unless product.available %}disabled{% endunless %}>
      {%- if product.available -%}Add to cart{%- else -%}Sold out{%- endif -%}
    </button>
  {%- endform -%}
</section>

{% schema %}
${json({ name: "Product", settings: [] })}
{% endschema %}
`;
}

function mainCollectionSection(): string {
  return `<section class="wrapper">
  <h1>{{ collection.title }}</h1>
  <div class="featured__grid">
    {%- for product in collection.products -%}
      {% render 'card-product', product: product %}
    {%- else -%}
      <p>No products in this collection yet.</p>
    {%- endfor -%}
  </div>
</section>

{% schema %}
${json({ name: "Collection", settings: [] })}
{% endschema %}
`;
}

function mainPageSection(): string {
  return `<section class="wrapper">
  <h1>{{ page.title }}</h1>
  <div class="rte">{{ page.content }}</div>
</section>

{% schema %}
${json({ name: "Page", settings: [] })}
{% endschema %}
`;
}

function settingsSchema(site: ExtractedSite): string {
  return json([
    {
      name: "theme_info",
      theme_name: `${site.brand} (generated)`,
      theme_version: "1.0.0",
      theme_author: "W3Tech Shopify Theme Generator",
      theme_documentation_url: "https://www.w3tech.co.in/popular-tools/shopify-theme-generator",
      theme_support_url: "https://www.w3tech.co.in/contact",
    },
    {
      name: "Colors",
      settings: [
        { type: "color", id: "accent_color", label: "Accent", default: site.colors.accent },
        { type: "color", id: "text_color", label: "Text", default: site.colors.text },
      ],
    },
  ]);
}

export async function zipTheme(files: ThemeFile[]): Promise<Buffer> {
  const zip = new JSZip();
  for (const file of files) {
    zip.file(file.path, file.contents);
  }
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
}
